#!/usr/bin/env bash

set -e
set -x

mode="--instant"
if [ $# -eq 1 ]; then
    mode=$1
fi

npm install

# Instant
if [ "${mode}" = "--instant" ]; then
    npm run test
elif [ "${mode}" = "--fast" ]; then
    npm run system-test:fast
fi