#!/usr/bin/env bash

set -e

mode="--instant"
if [ $# -eq 2 ]; then
    mode=$1
fi

npm install

# Instant
if [ "${mode}" = "--instant" ]; then
    npm run test
elif [ "${mode}" = "--fast" ]; then
    npm run system-test:fast
fi